### ISSUE TITLE
Request to publish the Source

### ISSUE THREAD

**Issue by gurice** [Zylence/10-fast-fingers-typing-bot-lightning_fingers#1]
Hello how are you? Can I contact you from here?

**Comment by gurice** [comment]
I would appreciate it if you would reply when you see this message.

**Comment by Zylence** [comment]
> Hello how are you? Can I contact you from here?
> I would appreciate it if you would reply when you see this message.

Hey, I'm doing fine. Thanks. How can I help you?

**Comment by gurice** [comment]
Do you have Discord?

**Comment by Zylence** [comment]
> Do you have Discord?

Sure, but I'd first like to know what this is about. Unfortunately I am a little short on time, so I can not join any other projects currently.

**Comment by gurice** [comment]
I'll tell you right away then.

**Comment by gurice** [comment]
I just discovered your software and it works fine, but it has some minor issues. I think your adjustments according to my country are wrong, I am from Turkey. If you don't mind, could you share the source codes with me? I am also a software developer and according to my country, your software does not work properly.

**Comment by gurice** [comment]
I am having problems with the letters İ, Ü, Ö, Ğ, Ç, which belong to my country.

**Comment by Zylence** [comment]
Oh alright. Thanks for reporting the issue. Honestly, did not even know that the software still works, neither that someone uses it. If I still have the source code, I'll see if I can push an update or share it directly. If I remember correctly, due to it being one of my first creations, the code quality was rather bad, which was why I concealed it in an exe in the first place ^^. I'll give it a look over the weekend.

**Comment by gurice** [comment]
It would be better for me if you share it, I want to adapt it directly to myself, I want to change a few more things.

**Comment by gurice** [comment]
It was a little difficult to discover your software, people cannot find it by searching this way. I would also like to inform you that my goal is definitely not to make a profit, but to adapt and use it according to my own needs.

**Comment by Zylence** [comment]
> It would be better for me if you share it, I want to adapt it directly to myself, I want to change a few more things.

Alright, if I still have it, I'll clean it up a little, not to embarrass myself too much, and push it. Move the exes to the release tab, as it should be. Then you can adjust the source as you wish and build yourself. Is this okay with you?

**Comment by gurice** [comment]
Never think of it as embarrassing, sir, even if you write "hello world" there, this is still an effort.

**Comment by gurice** [comment]
I want to fix one more thing. Is something like this possible? While writing the text, it creates backspace and corrects it, but I want it to pass without correcting it after I write it wrong.

**Comment by gurice** [comment]
I want it to pass by typing the wrong text without pressing the backspace button.

**Comment by Zylence** [comment]
> I want to fix one more thing. Is something like this possible? While writing the text, it creates backspace and corrects it, but I want it to pass without correcting it after I write it wrong.

I think it does not always correct the words. If I remember correctly, it should sometimes just mistype without correction. Although this may be rare.

**Comment by gurice** [comment]
Yes, but it's hard to time it during video evidence.

**Comment by gurice** [comment]
I don't want any corrections.

**Comment by gurice** [comment]
Just write it wrong and skip it.

**Comment by Zylence** [comment]
Ah, okay, when I find the source, you should definitely be able to adjust to your liking. But you need to give me some time. I need to go off now. I'll get back to you within the weekend.

**Comment by gurice** [comment]
Today is Saturday, tomorrow is Sunday. Will you be able to return within these 2 days?

**Comment by Zylence** [comment]
> Today is Saturday, tomorrow is Sunday. Will you be able to return within these 2 days?

yes

**Comment by gurice** [comment]
I don't recommend that we talk here. Would it be okay for you to talk via discord? 10FF officials are constantly checking.

**Comment by gurice** [comment]
how are you sir?

**Comment by Zylence** [comment]
> I don't recommend that we talk here. Would it be okay for you to talk via discord? 10FF officials are constantly checking.

ah I do not think they monitor this project ^^ I'd say they do not care, after all, they have not fixed their website in years... 
Also, I found the code, it did not need too much refactoring. The main reason for uploading an exe seems to have been obfuscation, but that really does not seem to be necessary.

**Comment by Zylence** [comment]
> how are you sir?

Thanks, good, and you? The sources are online, as well as requirements.txt and build instructions. Enjoy yourself :)

**Comment by Zylence** [comment]
If you make drastical improvements and do not want to keep them private, consider making a PR :^)

**Comment by gurice** [comment]
Thank you but I couldn't see the source file.

**Comment by gurice** [comment]
I see now that you opened a new folder and put it there, thank you very much sir.

**Comment by gurice** [comment]
I want to say it again. My goal is definitely not to make a profit, but to use it for my own benefit.

**Comment by Zylence** [comment]
> I want to say it again. My goal is definitely not to make a profit [...]

Okay, honestly, I think there is not much profit to be made, especially with the code in here. As far as I am aware, this can be achieved much easier, without the need for extra UI and stuff, by simply injecting JS into the browser via the dev console. 

>  [...] use it for my own benefit

GL with that! :)

I consider this issue closed

**Comment by gurice** [comment]
I have reviewed your software and thank you very much for your extensive efforts. Where can I cancel this correction part? If you just tell me this, I will pray for you.

**Comment by Zylence** [comment]
> I have reviewed your software and thank you very much for your extensive efforts. Where can I cancel this correction part? If you just tell me this, I will pray for you.

should be around here
https://github.com/Zylence/10-fast-fingers-typing-bot-lightning_fingers/blob/ad89ba3f8439de0c3f653c9a7f3adcffa9ef45d9/main/main.py#L376

**Comment by gurice** [comment]
Thank you very much, I offer my respects. Have a nice day, good work, sir.
